########## Customer CMS API###############


### Root api
GET http://localhost:8000/

### Create new user
POST http://localhost:8000/api/v1/user
Content-Type: application/json

{
    "fname":"Bijay",
    "lname":"Nagarkoti",
    "email":"b@b.com",
    "password":"12345678",
    "phone":"0433030330",
    "address":"Sydney, NSW",
    "gender":"Male"
}


### Verify Admin Email
PATCH http://localhost:8000/api/v1/user/email-verification
Content-Type: application/json

{
    "pin":"474367",
    "email":"b@b.com"
}
### Login User
POST http://localhost:8000/api/v1/user/login
Content-Type: application/json

{
    "email":"b@b.com",
    "password":"12345678"
}


### Logout User
POST http://localhost:8000/api/v1/user/logout
Content-Type: application/json

{
   "accessJWT": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJAYi5jb20iLCJpYXQiOjE2NDYzNjkwMDMsImV4cCI6MTY0NjM2OTkwM30.Y8yEjRUIvJoZj35QI4hMHWCvJAIqVAnTbVQ9AnxKzbw",
    "refreshJWT": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJAYi5jb20iLCJpYXQiOjE2NDYzNjkwMDMsImV4cCI6MTY0ODk2MTAwM30.96nxwmnxJJej4PlrM_ytgWRhnFplft2GuQYQsFKGotU"
}


############################## Token Router ###############

### get new access token

GET http://localhost:8000/api/v1/user/token
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFwQGdtYWlsLmNvbSIsImlhdCI6MTY0NDk3NzY0NCwiZXhwIjoxNjQ3NTY5NjQ0fQ.STolgmiOIOTWBhGmjaaO_RUAhR7ixZVE1Mcm3V5nnZY

