########## Customer CMS API###############


### Root api
GET http://localhost:8000/

### Create new user
POST http://localhost:8000/api/v1/user
Content-Type: application/json

{
    "fname":"Bijay",
    "lname":"Nagarkoti",
    "email":"b@b.com",
    "password":"12345678",
    "phone":"0433030330",
    "address":"Sydney, NSW",
    "gender":"Male"
}


### Verify Admin Email
PATCH http://localhost:8000/api/v1/user/email-verification
Content-Type: application/json

{
    "pin":"474367",
    "email":"b@b.com"
}
### Login User
POST http://localhost:8000/api/v1/user/login
Content-Type: application/json

{
    "email":"a@b.com",
    "password":"12345678"
}
### User forgot password otp request
POST http://localhost:8000/api/v1/token/request-otp
Content-Type: application/json

{
   "email":"a@b.com" 
}


### Logout User
POST http://localhost:8000/api/v1/user/logout
Content-Type: application/json

{
   "accessJWT": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJAYi5jb20iLCJpYXQiOjE2NDYzNjkwMDMsImV4cCI6MTY0NjM2OTkwM30.Y8yEjRUIvJoZj35QI4hMHWCvJAIqVAnTbVQ9AnxKzbw",
    "refreshJWT": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJAYi5jb20iLCJpYXQiOjE2NDYzNjkwMDMsImV4cCI6MTY0ODk2MTAwM30.96nxwmnxJJej4PlrM_ytgWRhnFplft2GuQYQsFKGotU"
}
### User Update Password
POST  http://localhost:8000/api/v1/user/password-update
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYi5jb20iLCJpYXQiOjE2NDY3OTgwNDgsImV4cCI6MTY0Njc5ODk0OH0.S5HclMIZur0buGk_8vHkOy9SXTMamMjFDJfvcFKpTU8

{
   "currentPassword":"12345678",
   "password":"12345678io"
}

### Reset new password
POST  http://localhost:8000/api/v1/user/reset-password
Content-Type: application/json

{
    "otp":232323,
   "newpassword":"12345678io"
}

// 2!Aa1111

############################## Token Router ###############

### get new access token

GET http://localhost:8000/api/v1/token
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJAYi5jb20iLCJpYXQiOjE2NDYzNzE0NDQsImV4cCI6MTY0ODk2MzQ0NH0.3pHXZ2-D16ZQnpYdRNwk7MXFWKEQbukHxIFkFY1zofk

