##### User CMS API


### Root api
GET http://localhost:8000/

### Create new user
POST http://localhost:8000/api/v1/user
Content-Type: application/json

{
    "fname":"Bijay",
    "lname":"Nagarkoti",
    "email":"b@ab.com",
    "password":"12345678",
    "phone":"0433030330",
    "address":"Sydney, NSW",
    "gender":"Male"
}


##### Email APIs

### Verify Admin Email
PATCH http://localhost:8000/api/v1/user/email-verification
Content-Type: application/json

{
    "pin":"495308",
    "email":"b@ab.com"
}